import {auth,db,getDB,saveDB,saveSettings,saveUserProfile,esc,initials,uid,logout,protect,nextCoachId} from "./app.js";
import {initializeApp,getApps} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {firebaseConfig} from "./firebase.js";
import {getAuth,createUserWithEmailAndPassword,signOut as secondarySignOut} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import {set,ref} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-database.js";
const session=await protect("admin");
if(session){let dbData=await getDB();const views=document.querySelectorAll(".view");document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));n.classList.add("active");views.forEach(v=>v.classList.add("hidden"));document.querySelector("#"+n.dataset.view).classList.remove("hidden");pageTitle.textContent=n.textContent;renderAll()});
async function renderAll(){dbData=await getDB();stats.innerHTML=[["Students",(dbData.students||[]).length],["Coaches",(dbData.coaches||[]).length],["Branches",(dbData.branches||[]).length],["Academies",(dbData.academies||[]).length]].map(x=>`<div class="stat"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");recentStudents.innerHTML=studentRows((dbData.students||[]).slice(-5).reverse());studentsTable.innerHTML=studentRows(dbData.students||[]);coachesTable.innerHTML=coachRows();branchesList.innerHTML=(dbData.branches||[]).map((x,i)=>`<div class="record"><b>${esc(x)}</b> <button class="mini" onclick="removeBranch(${i})">Remove</button></div>`).join("")||'<div class="empty">No branches</div>';academiesList.innerHTML=(dbData.academies||[]).map((x,i)=>`<div class="record"><b>${esc(x)}</b> <button class="mini" onclick="removeAcademy(${i})">Remove</button></div>`).join("")||'<div class="empty">No academies</div>'}
function studentRows(list){if(!list.length)return'<div class="empty">No students found.</div>';return`<table class="table"><thead><tr><th>Student</th><th>ID</th><th>Branch</th><th>Academy</th><th>Belt</th><th>Coach</th><th>Action</th></tr></thead><tbody>${list.map(s=>{let c=(dbData.coaches||[]).find(x=>x.id===s.coachId||x.uid===s.coachId);return`<tr><td><div class="person"><div class="avatar">${s.photo?`<img class="avatar" src="${s.photo}">`:initials(s.name)}</div><b>${esc(s.name)}</b></div></td><td>${esc(s.studentId)}</td><td>${esc(s.branch)}</td><td>${esc(s.academy)}</td><td>${esc(s.belt||"White")}</td><td>${esc(c?.name||"Unassigned")}</td><td><div class="action-row"><button class="mini" onclick="editStudent('${s.id}')">Edit</button><button class="mini" onclick="openCard('${s.studentId}')">ID Card</button></div></td></tr>`}).join("")}</tbody></table>`}
function coachRows(){if(!(dbData.coaches||[]).length)return'<div class="empty">No coaches.</div>';return`<table class="table"><thead><tr><th>Name</th><th>Email</th><th>Students</th></tr></thead><tbody>${dbData.coaches.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.email)}</td><td>${(dbData.students||[]).filter(s=>s.coachId===c.id||s.coachId===c.uid).length}</td></tr>`).join("")}</tbody></table>`}
window.editStudent=async id=>{let s=(await getDB()).students.find(x=>x.id===id),d=await getDB();modal.classList.remove("hidden");modal.innerHTML=`<div class="modal-box"><div class="modal-head"><h2>Edit Student</h2><button class="modal-close" onclick="closeModal()">×</button></div><form id="editForm" class="form-card"><label>Name<input id="eName" value="${esc(s.name)}" required></label><label>Branch<select id="eBranch">${(d.branches||[]).map(x=>`<option ${x===s.branch?"selected":""}>${esc(x)}</option>`).join("")}</select></label><label>Academy<select id="eAcademy">${(d.academies||[]).map(x=>`<option ${x===s.academy?"selected":""}>${esc(x)}</option>`).join("")}</select></label><label>Coach<select id="eCoach"><option value="">Unassigned</option>${(d.coaches||[]).map(c=>`<option value="${c.uid||c.id}" ${(c.uid||c.id)===s.coachId?"selected":""}>${esc(c.name)}</option>`).join("")}</select></label><label>Belt<select id="eBelt">${["White","Yellow","Green","Blue","Red","Black"].map(x=>`<option ${x===s.belt?"selected":""}>${x}</option>`).join("")}</select></label><button class="btn primary">Save Changes</button></form></div>`;editForm.onsubmit=async e=>{e.preventDefault();let d2=await getDB(),x=d2.students.find(z=>z.id===id);Object.assign(x,{name:eName.value,branch:eBranch.value,academy:eAcademy.value,coachId:eCoach.value,belt:eBelt.value});await saveDB(d2);closeModal();renderAll()}};
window.closeModal=()=>modal.classList.add("hidden");window.openCard=id=>window.open("id-card.html?id="+encodeURIComponent(id),"_blank");
addCoach.onclick=async()=>{modal.classList.remove("hidden");modal.innerHTML=`<div class="modal-box"><div class="modal-head"><h2>Add Coach</h2><button class="modal-close" onclick="closeModal()">×</button></div><form id="coachForm" class="form-card"><label>Name<input id="cName" required></label><label>Email<input id="cEmail" type="email" required></label><label>Password<input id="cPass" minlength="6" required></label><label>Branch<select id="cBranch" required>${(dbData.branches||[]).map(x=>`<option>${esc(x)}</option>`).join("")}</select></label><label>Academy<select id="cAcademy" required>${(dbData.academies||[]).map(x=>`<option>${esc(x)}</option>`).join("")}</select></label><button class="btn primary">Create Coach Account</button></form></div>`;coachForm.onsubmit=async e=>{e.preventDefault();try{const app2=getApps().find(a=>a.name==="coachCreator")||initializeApp(firebaseConfig,"coachCreator"),a=getAuth(app2),cred=await createUserWithEmailAndPassword(a,cEmail.value.trim().toLowerCase(),cPass.value),d=await getDB(),coach={id:cred.user.uid,uid:cred.user.uid,coachId:nextCoachId(d),name:cName.value.trim(),email:cEmail.value.trim().toLowerCase(),branch:cBranch.value,academy:cAcademy.value,role:"coach",createdAt:new Date().toISOString()};await set(ref(db,`coaches/${cred.user.uid}`),coach);await secondarySignOut(a);closeModal();renderAll()}catch(err){alert(err.message)}}};
addBranch.onclick=()=>addItem("branch");addAcademy.onclick=()=>addItem("academy");async function addItem(type){let label=type==="branch"?"Branch":"Academy",v=prompt("Enter "+label+" name");if(!v)return;let d=await getDB(),arr=type==="branch"?(d.branches||[]):(d.academies||[]);if(!arr.includes(v.trim()))arr.push(v.trim());await saveSettings(d);renderAll()}window.removeBranch=async i=>{let d=await getDB();if(confirm("Remove branch?")){d.branches.splice(i,1);await saveSettings(d);renderAll()}};window.removeAcademy=async i=>{let d=await getDB();if(confirm("Remove academy?")){d.academies.splice(i,1);await saveSettings(d);renderAll()}};studentSearch.oninput=async()=>{let q=studentSearch.value.toLowerCase(),d=await getDB();studentsTable.innerHTML=studentRows((d.students||[]).filter(s=>(s.name+s.studentId+s.branch+s.academy).toLowerCase().includes(q)))};renderAll()}
